DROP DATABASE PublishingJPADB;
CREATE DATABASE PublishingJPADB;
USE PublishingJPADB;

CREATE TABLE CATEGORY (
       ID BIGINT NOT NULL AUTO_INCREMENT
     , NAME VARCHAR(100) NOT NULL
     , VERSION INT NOT NULL DEFAULT 0
     , UNIQUE UQ_CATEGORY_1 (NAME)
     , PRIMARY KEY (ID)
);

CREATE TABLE BOOK (
       ID BIGINT NOT NULL AUTO_INCREMENT
     , CATEGORY_ID BIGINT NOT NULL
     , ISBN VARCHAR(13) NOT NULL
     , TITLE VARCHAR(500) NOT NULL
     , PRICE DECIMAL(4,2) NOT NULL
     , VERSION INT NOT NULL DEFAULT 0
     , UNIQUE UQ_BOOK_1 (ISBN)
     , PRIMARY KEY (ID)
     , CONSTRAINT FK_BOOK_1 FOREIGN KEY (CATEGORY_ID)
                  REFERENCES CATEGORY (ID) 
);

CREATE TABLE AUTHOR(
	ID BIGINT NOT NULL AUTO_INCREMENT
	, FIRST_NAME VARCHAR(60)
	, LAST_NAME VARCHAR(60)
	, DESCRIPTION VARCHAR(1200)
    , UNIQUE UQ_AUTHOR_1 (FIRST_NAME, LAST_NAME)
	, PRIMARY KEY (ID)
);

CREATE TABLE AUTHOR_BOOK(
    AUTHOR_ID BIGINT NOT NULL
	, BOOK_ID BIGINT NOT NULL 
    , CONSTRAINT FK_AUHTOR_BOOK_2 FOREIGN KEY (AUTHOR_ID)
     	REFERENCES AUTHOR (ID) ON DELETE CASCADE
	, CONSTRAINT FK_AUTHOR_BOOK_1 FOREIGN KEY (BOOK_ID)
         REFERENCES BOOK (ID) ON DELETE CASCADE

);
